// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_3_Matrix_Vector_Activa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY,
        weight_V_V_TDATA,
        weight_V_V_TVALID,
        weight_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [191:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [23:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;
input  [95:0] weight_V_V_TDATA;
input   weight_V_V_TVALID;
output   weight_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;
reg weight_V_V_TREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln248_fu_252_p2;
wire   [0:0] icmp_ln252_fu_267_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln271_reg_1470;
reg   [0:0] icmp_ln271_reg_1470_pp0_iter1_reg;
reg    weight_V_V_TDATA_blk_n;
reg   [6:0] i_0_reg_231;
reg    ap_predicate_op26_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state4_io;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] i_fu_258_p2;
wire   [0:0] icmp_ln271_fu_281_p2;
wire   [3:0] wgt_M_instance_0_V_fu_287_p1;
reg  signed [3:0] wgt_M_instance_0_V_reg_1475;
reg  signed [3:0] wgt_M_instance_1_V_reg_1480;
reg  signed [3:0] wgt_M_instance_2_V_reg_1485;
reg  signed [3:0] wgt_M_instance_3_V_reg_1490;
reg  signed [3:0] wgt_M_instance_4_V_reg_1495;
reg  signed [3:0] wgt_M_instance_5_V_reg_1500;
reg  signed [3:0] wgt_M_instance_6_V_reg_1505;
reg  signed [3:0] wgt_M_instance_7_V_reg_1510;
reg  signed [3:0] wgt_M_instance_8_V_reg_1515;
reg  signed [3:0] wgt_M_instance_9_V_reg_1520;
reg  signed [3:0] wgt_M_instance_10_s_reg_1525;
reg  signed [3:0] wgt_M_instance_11_s_reg_1530;
reg  signed [3:0] wgt_M_instance_12_s_reg_1535;
reg  signed [3:0] wgt_M_instance_13_s_reg_1540;
reg  signed [3:0] wgt_M_instance_14_s_reg_1545;
reg  signed [3:0] wgt_M_instance_15_s_reg_1550;
reg  signed [3:0] wgt_M_instance_16_s_reg_1555;
reg  signed [3:0] wgt_M_instance_17_s_reg_1560;
reg  signed [3:0] wgt_M_instance_18_s_reg_1565;
reg  signed [3:0] wgt_M_instance_19_s_reg_1570;
reg  signed [3:0] wgt_M_instance_20_s_reg_1575;
reg  signed [3:0] wgt_M_instance_21_s_reg_1580;
reg  signed [3:0] wgt_M_instance_22_s_reg_1585;
reg  signed [3:0] wgt_M_instance_23_s_reg_1590;
wire   [12:0] add_ln700_fu_1199_p2;
reg   [12:0] add_ln700_reg_1595;
wire   [13:0] add_ln700_3_fu_1215_p2;
reg   [13:0] add_ln700_3_reg_1600;
wire   [13:0] add_ln700_6_fu_1231_p2;
reg   [13:0] add_ln700_6_reg_1605;
wire   [13:0] add_ln700_8_fu_1247_p2;
reg   [13:0] add_ln700_8_reg_1610;
wire   [13:0] add_ln700_12_fu_1263_p2;
reg   [13:0] add_ln700_12_reg_1615;
wire   [13:0] add_ln700_14_fu_1279_p2;
reg   [13:0] add_ln700_14_reg_1620;
wire   [13:0] add_ln700_17_fu_1295_p2;
reg   [13:0] add_ln700_17_reg_1625;
wire   [13:0] add_ln700_20_fu_1321_p2;
reg   [13:0] add_ln700_20_reg_1630;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg   [23:0] tmp_V_fu_196;
wire   [23:0] tmp_V_3_fu_1419_p2;
reg   [31:0] sf_1_fu_200;
wire   [31:0] sf_fu_521_p2;
reg   [31:0] nf_2_fu_204;
wire   [31:0] nf_3_fu_541_p3;
reg   [191:0] inElem_V_fu_208;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] nf_fu_535_p2;
wire   [7:0] trunc_ln647_fu_557_p1;
wire   [7:0] mul_ln1352_fu_568_p0;
wire  signed [11:0] mul_ln1352_fu_568_p2;
wire   [7:0] arg_V_read_assign_1_fu_578_p4;
wire   [7:0] mul_ln1352_1_fu_595_p0;
wire  signed [11:0] mul_ln1352_1_fu_595_p2;
wire   [7:0] arg_V_read_assign_2_fu_605_p4;
wire   [7:0] mul_ln1352_2_fu_622_p0;
wire  signed [11:0] mul_ln1352_2_fu_622_p2;
wire   [7:0] arg_V_read_assign_3_fu_632_p4;
wire   [7:0] mul_ln1352_3_fu_649_p0;
wire  signed [11:0] mul_ln1352_3_fu_649_p2;
wire   [7:0] arg_V_read_assign_4_fu_659_p4;
wire   [7:0] mul_ln1352_4_fu_676_p0;
wire  signed [11:0] mul_ln1352_4_fu_676_p2;
wire   [7:0] arg_V_read_assign_5_fu_686_p4;
wire   [7:0] mul_ln1352_5_fu_703_p0;
wire  signed [11:0] mul_ln1352_5_fu_703_p2;
wire   [7:0] arg_V_read_assign_6_fu_713_p4;
wire   [7:0] mul_ln1352_6_fu_730_p0;
wire  signed [11:0] mul_ln1352_6_fu_730_p2;
wire   [7:0] arg_V_read_assign_7_fu_740_p4;
wire   [7:0] mul_ln1352_7_fu_757_p0;
wire  signed [11:0] mul_ln1352_7_fu_757_p2;
wire   [7:0] arg_V_read_assign_8_fu_767_p4;
wire   [7:0] mul_ln1352_8_fu_784_p0;
wire  signed [11:0] mul_ln1352_8_fu_784_p2;
wire   [7:0] arg_V_read_assign_9_fu_794_p4;
wire   [7:0] mul_ln1352_9_fu_811_p0;
wire  signed [11:0] mul_ln1352_9_fu_811_p2;
wire   [7:0] arg_V_read_assign_s_fu_821_p4;
wire   [7:0] mul_ln1352_10_fu_838_p0;
wire  signed [11:0] mul_ln1352_10_fu_838_p2;
wire   [7:0] arg_V_read_assign_10_fu_848_p4;
wire   [7:0] mul_ln1352_11_fu_865_p0;
wire  signed [11:0] mul_ln1352_11_fu_865_p2;
wire   [7:0] arg_V_read_assign_11_fu_875_p4;
wire   [7:0] mul_ln1352_12_fu_892_p0;
wire  signed [11:0] mul_ln1352_12_fu_892_p2;
wire   [7:0] arg_V_read_assign_12_fu_902_p4;
wire   [7:0] mul_ln1352_13_fu_919_p0;
wire  signed [11:0] mul_ln1352_13_fu_919_p2;
wire   [7:0] arg_V_read_assign_13_fu_929_p4;
wire   [7:0] mul_ln1352_14_fu_946_p0;
wire  signed [11:0] mul_ln1352_14_fu_946_p2;
wire   [7:0] arg_V_read_assign_14_fu_956_p4;
wire   [7:0] mul_ln1352_15_fu_973_p0;
wire  signed [11:0] mul_ln1352_15_fu_973_p2;
wire   [7:0] arg_V_read_assign_15_fu_983_p4;
wire   [7:0] mul_ln1352_16_fu_1000_p0;
wire  signed [11:0] mul_ln1352_16_fu_1000_p2;
wire   [7:0] arg_V_read_assign_16_fu_1010_p4;
wire   [7:0] mul_ln1352_17_fu_1027_p0;
wire  signed [11:0] mul_ln1352_17_fu_1027_p2;
wire   [7:0] arg_V_read_assign_17_fu_1037_p4;
wire   [7:0] mul_ln1352_18_fu_1054_p0;
wire  signed [11:0] mul_ln1352_18_fu_1054_p2;
wire   [7:0] arg_V_read_assign_18_fu_1064_p4;
wire   [7:0] mul_ln1352_19_fu_1081_p0;
wire  signed [11:0] mul_ln1352_19_fu_1081_p2;
wire   [7:0] arg_V_read_assign_19_fu_1091_p4;
wire   [7:0] mul_ln1352_20_fu_1108_p0;
wire  signed [11:0] mul_ln1352_20_fu_1108_p2;
wire   [7:0] arg_V_read_assign_20_fu_1118_p4;
wire   [7:0] mul_ln1352_21_fu_1135_p0;
wire  signed [11:0] mul_ln1352_21_fu_1135_p2;
wire   [7:0] arg_V_read_assign_21_fu_1145_p4;
wire   [7:0] mul_ln1352_22_fu_1162_p0;
wire  signed [11:0] mul_ln1352_22_fu_1162_p2;
wire   [7:0] arg_V_read_assign_22_fu_1172_p4;
wire   [7:0] mul_ln1352_23_fu_1189_p0;
wire  signed [11:0] mul_ln1352_23_fu_1189_p2;
wire  signed [12:0] sext_ln170_22_fu_1168_p1;
wire  signed [12:0] sext_ln170_21_fu_1141_p1;
wire  signed [12:0] sext_ln170_19_fu_1087_p1;
wire  signed [12:0] sext_ln170_17_fu_1033_p1;
wire   [12:0] add_ln700_2_fu_1205_p2;
wire  signed [13:0] sext_ln170_20_fu_1114_p1;
wire  signed [13:0] sext_ln700_2_fu_1211_p1;
wire  signed [12:0] sext_ln170_13_fu_925_p1;
wire  signed [12:0] sext_ln170_11_fu_871_p1;
wire   [12:0] add_ln700_5_fu_1221_p2;
wire  signed [13:0] sext_ln170_18_fu_1060_p1;
wire  signed [13:0] sext_ln700_4_fu_1227_p1;
wire  signed [12:0] sext_ln170_16_fu_1006_p1;
wire  signed [12:0] sext_ln170_14_fu_952_p1;
wire   [12:0] add_ln700_7_fu_1237_p2;
wire  signed [13:0] sext_ln170_12_fu_898_p1;
wire  signed [13:0] sext_ln700_6_fu_1243_p1;
wire  signed [12:0] sext_ln170_fu_574_p1;
wire  signed [12:0] sext_ln170_1_fu_601_p1;
wire   [12:0] add_ln700_11_fu_1253_p2;
wire  signed [13:0] sext_ln170_15_fu_979_p1;
wire  signed [13:0] sext_ln700_9_fu_1259_p1;
wire  signed [12:0] sext_ln170_3_fu_655_p1;
wire  signed [12:0] sext_ln170_4_fu_682_p1;
wire   [12:0] add_ln700_13_fu_1269_p2;
wire  signed [13:0] sext_ln170_2_fu_628_p1;
wire  signed [13:0] sext_ln700_11_fu_1275_p1;
wire  signed [12:0] sext_ln170_6_fu_736_p1;
wire  signed [12:0] sext_ln170_7_fu_763_p1;
wire   [12:0] add_ln700_16_fu_1285_p2;
wire  signed [13:0] sext_ln170_5_fu_709_p1;
wire  signed [13:0] sext_ln700_14_fu_1291_p1;
wire  signed [12:0] sext_ln170_10_fu_844_p1;
wire  signed [12:0] sext_ln170_8_fu_790_p1;
wire   [12:0] add_ln700_18_fu_1301_p2;
wire  signed [12:0] sext_ln700_fu_1195_p1;
wire  signed [12:0] sext_ln170_9_fu_817_p1;
wire   [12:0] add_ln700_19_fu_1311_p2;
wire  signed [13:0] sext_ln700_16_fu_1307_p1;
wire  signed [13:0] sext_ln700_17_fu_1317_p1;
wire   [23:0] res_V_fu_1330_p3;
wire  signed [23:0] sext_ln700_1_fu_1337_p1;
wire   [23:0] add_ln700_1_fu_1340_p2;
wire  signed [23:0] sext_ln700_3_fu_1346_p1;
wire  signed [14:0] sext_ln700_5_fu_1355_p1;
wire  signed [14:0] sext_ln700_7_fu_1358_p1;
wire   [14:0] add_ln700_9_fu_1361_p2;
wire   [23:0] add_ln700_4_fu_1349_p2;
wire  signed [23:0] sext_ln700_8_fu_1367_p1;
wire  signed [14:0] sext_ln700_10_fu_1377_p1;
wire  signed [14:0] sext_ln700_12_fu_1380_p1;
wire   [14:0] add_ln700_15_fu_1383_p2;
wire  signed [14:0] sext_ln700_15_fu_1393_p1;
wire  signed [14:0] sext_ln700_18_fu_1396_p1;
wire   [14:0] add_ln700_21_fu_1399_p2;
wire  signed [15:0] sext_ln700_13_fu_1389_p1;
wire  signed [15:0] sext_ln700_19_fu_1405_p1;
wire   [15:0] add_ln700_22_fu_1409_p2;
wire   [23:0] add_ln700_10_fu_1371_p2;
wire  signed [23:0] sext_ln700_20_fu_1415_p1;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [11:0] mul_ln1352_10_fu_838_p00;
wire   [11:0] mul_ln1352_11_fu_865_p00;
wire   [11:0] mul_ln1352_12_fu_892_p00;
wire   [11:0] mul_ln1352_13_fu_919_p00;
wire   [11:0] mul_ln1352_14_fu_946_p00;
wire   [11:0] mul_ln1352_15_fu_973_p00;
wire   [11:0] mul_ln1352_16_fu_1000_p00;
wire   [11:0] mul_ln1352_17_fu_1027_p00;
wire   [11:0] mul_ln1352_18_fu_1054_p00;
wire   [11:0] mul_ln1352_19_fu_1081_p00;
wire   [11:0] mul_ln1352_1_fu_595_p00;
wire   [11:0] mul_ln1352_20_fu_1108_p00;
wire   [11:0] mul_ln1352_21_fu_1135_p00;
wire   [11:0] mul_ln1352_22_fu_1162_p00;
wire   [11:0] mul_ln1352_23_fu_1189_p00;
wire   [11:0] mul_ln1352_2_fu_622_p00;
wire   [11:0] mul_ln1352_3_fu_649_p00;
wire   [11:0] mul_ln1352_4_fu_676_p00;
wire   [11:0] mul_ln1352_5_fu_703_p00;
wire   [11:0] mul_ln1352_6_fu_730_p00;
wire   [11:0] mul_ln1352_7_fu_757_p00;
wire   [11:0] mul_ln1352_8_fu_784_p00;
wire   [11:0] mul_ln1352_9_fu_811_p00;
wire   [11:0] mul_ln1352_fu_568_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U1(
    .din0(mul_ln1352_fu_568_p0),
    .din1(wgt_M_instance_0_V_reg_1475),
    .dout(mul_ln1352_fu_568_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U2(
    .din0(mul_ln1352_1_fu_595_p0),
    .din1(wgt_M_instance_1_V_reg_1480),
    .dout(mul_ln1352_1_fu_595_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U3(
    .din0(mul_ln1352_2_fu_622_p0),
    .din1(wgt_M_instance_2_V_reg_1485),
    .dout(mul_ln1352_2_fu_622_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U4(
    .din0(mul_ln1352_3_fu_649_p0),
    .din1(wgt_M_instance_3_V_reg_1490),
    .dout(mul_ln1352_3_fu_649_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U5(
    .din0(mul_ln1352_4_fu_676_p0),
    .din1(wgt_M_instance_4_V_reg_1495),
    .dout(mul_ln1352_4_fu_676_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U6(
    .din0(mul_ln1352_5_fu_703_p0),
    .din1(wgt_M_instance_5_V_reg_1500),
    .dout(mul_ln1352_5_fu_703_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U7(
    .din0(mul_ln1352_6_fu_730_p0),
    .din1(wgt_M_instance_6_V_reg_1505),
    .dout(mul_ln1352_6_fu_730_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U8(
    .din0(mul_ln1352_7_fu_757_p0),
    .din1(wgt_M_instance_7_V_reg_1510),
    .dout(mul_ln1352_7_fu_757_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U9(
    .din0(mul_ln1352_8_fu_784_p0),
    .din1(wgt_M_instance_8_V_reg_1515),
    .dout(mul_ln1352_8_fu_784_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U10(
    .din0(mul_ln1352_9_fu_811_p0),
    .din1(wgt_M_instance_9_V_reg_1520),
    .dout(mul_ln1352_9_fu_811_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U11(
    .din0(mul_ln1352_10_fu_838_p0),
    .din1(wgt_M_instance_10_s_reg_1525),
    .dout(mul_ln1352_10_fu_838_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U12(
    .din0(mul_ln1352_11_fu_865_p0),
    .din1(wgt_M_instance_11_s_reg_1530),
    .dout(mul_ln1352_11_fu_865_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U13(
    .din0(mul_ln1352_12_fu_892_p0),
    .din1(wgt_M_instance_12_s_reg_1535),
    .dout(mul_ln1352_12_fu_892_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U14(
    .din0(mul_ln1352_13_fu_919_p0),
    .din1(wgt_M_instance_13_s_reg_1540),
    .dout(mul_ln1352_13_fu_919_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U15(
    .din0(mul_ln1352_14_fu_946_p0),
    .din1(wgt_M_instance_14_s_reg_1545),
    .dout(mul_ln1352_14_fu_946_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U16(
    .din0(mul_ln1352_15_fu_973_p0),
    .din1(wgt_M_instance_15_s_reg_1550),
    .dout(mul_ln1352_15_fu_973_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U17(
    .din0(mul_ln1352_16_fu_1000_p0),
    .din1(wgt_M_instance_16_s_reg_1555),
    .dout(mul_ln1352_16_fu_1000_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U18(
    .din0(mul_ln1352_17_fu_1027_p0),
    .din1(wgt_M_instance_17_s_reg_1560),
    .dout(mul_ln1352_17_fu_1027_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U19(
    .din0(mul_ln1352_18_fu_1054_p0),
    .din1(wgt_M_instance_18_s_reg_1565),
    .dout(mul_ln1352_18_fu_1054_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U20(
    .din0(mul_ln1352_19_fu_1081_p0),
    .din1(wgt_M_instance_19_s_reg_1570),
    .dout(mul_ln1352_19_fu_1081_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U21(
    .din0(mul_ln1352_20_fu_1108_p0),
    .din1(wgt_M_instance_20_s_reg_1575),
    .dout(mul_ln1352_20_fu_1108_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U22(
    .din0(mul_ln1352_21_fu_1135_p0),
    .din1(wgt_M_instance_21_s_reg_1580),
    .dout(mul_ln1352_21_fu_1135_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U23(
    .din0(mul_ln1352_22_fu_1162_p0),
    .din1(wgt_M_instance_22_s_reg_1585),
    .dout(mul_ln1352_22_fu_1162_p2)
);

StreamingFCLayer_Batch_3_StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
StreamingFCLayer_Batch_3_mul_8ns_4s_12_1_1_U24(
    .din0(mul_ln1352_23_fu_1189_p0),
    .din1(wgt_M_instance_23_s_reg_1590),
    .dout(mul_ln1352_23_fu_1189_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_reg_231 <= i_fu_258_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_231 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_281_p2 == 1'd1) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nf_2_fu_204 <= nf_3_fu_541_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_2_fu_204 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_281_p2 == 1'd0) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sf_1_fu_200 <= sf_fu_521_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_fu_281_p2 == 1'd1) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        sf_1_fu_200 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln700_12_reg_1615 <= add_ln700_12_fu_1263_p2;
        add_ln700_14_reg_1620 <= add_ln700_14_fu_1279_p2;
        add_ln700_17_reg_1625 <= add_ln700_17_fu_1295_p2;
        add_ln700_20_reg_1630 <= add_ln700_20_fu_1321_p2;
        add_ln700_3_reg_1600 <= add_ln700_3_fu_1215_p2;
        add_ln700_6_reg_1605 <= add_ln700_6_fu_1231_p2;
        add_ln700_8_reg_1610 <= add_ln700_8_fu_1247_p2;
        add_ln700_reg_1595 <= add_ln700_fu_1199_p2;
        icmp_ln271_reg_1470_pp0_iter1_reg <= icmp_ln271_reg_1470;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_252_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln271_reg_1470 <= icmp_ln271_fu_281_p2;
        wgt_M_instance_0_V_reg_1475 <= wgt_M_instance_0_V_fu_287_p1;
        wgt_M_instance_10_s_reg_1525 <= {{weight_V_V_TDATA[43:40]}};
        wgt_M_instance_11_s_reg_1530 <= {{weight_V_V_TDATA[47:44]}};
        wgt_M_instance_12_s_reg_1535 <= {{weight_V_V_TDATA[51:48]}};
        wgt_M_instance_13_s_reg_1540 <= {{weight_V_V_TDATA[55:52]}};
        wgt_M_instance_14_s_reg_1545 <= {{weight_V_V_TDATA[59:56]}};
        wgt_M_instance_15_s_reg_1550 <= {{weight_V_V_TDATA[63:60]}};
        wgt_M_instance_16_s_reg_1555 <= {{weight_V_V_TDATA[67:64]}};
        wgt_M_instance_17_s_reg_1560 <= {{weight_V_V_TDATA[71:68]}};
        wgt_M_instance_18_s_reg_1565 <= {{weight_V_V_TDATA[75:72]}};
        wgt_M_instance_19_s_reg_1570 <= {{weight_V_V_TDATA[79:76]}};
        wgt_M_instance_1_V_reg_1480 <= {{weight_V_V_TDATA[7:4]}};
        wgt_M_instance_20_s_reg_1575 <= {{weight_V_V_TDATA[83:80]}};
        wgt_M_instance_21_s_reg_1580 <= {{weight_V_V_TDATA[87:84]}};
        wgt_M_instance_22_s_reg_1585 <= {{weight_V_V_TDATA[91:88]}};
        wgt_M_instance_23_s_reg_1590 <= {{weight_V_V_TDATA[95:92]}};
        wgt_M_instance_2_V_reg_1485 <= {{weight_V_V_TDATA[11:8]}};
        wgt_M_instance_3_V_reg_1490 <= {{weight_V_V_TDATA[15:12]}};
        wgt_M_instance_4_V_reg_1495 <= {{weight_V_V_TDATA[19:16]}};
        wgt_M_instance_5_V_reg_1500 <= {{weight_V_V_TDATA[23:20]}};
        wgt_M_instance_6_V_reg_1505 <= {{weight_V_V_TDATA[27:24]}};
        wgt_M_instance_7_V_reg_1510 <= {{weight_V_V_TDATA[31:28]}};
        wgt_M_instance_8_V_reg_1515 <= {{weight_V_V_TDATA[35:32]}};
        wgt_M_instance_9_V_reg_1520 <= {{weight_V_V_TDATA[39:36]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln252_fu_267_p2 == 1'd1) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inElem_V_fu_208 <= in_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tmp_V_fu_196 <= tmp_V_3_fu_1419_p2;
    end
end

always @ (*) begin
    if ((icmp_ln248_fu_252_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln252_fu_267_p2 == 1'd1) & (icmp_ln248_fu_252_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op26_read_state2 == 1'b1))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln271_reg_1470_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln271_reg_1470_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln248_fu_252_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_V_V_TDATA_blk_n = weight_V_V_TVALID;
    end else begin
        weight_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln248_fu_252_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weight_V_V_TREADY = 1'b1;
    end else begin
        weight_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln248_fu_252_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((icmp_ln248_fu_252_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln700_10_fu_1371_p2 = ($signed(add_ln700_4_fu_1349_p2) + $signed(sext_ln700_8_fu_1367_p1));

assign add_ln700_11_fu_1253_p2 = ($signed(sext_ln170_fu_574_p1) + $signed(sext_ln170_1_fu_601_p1));

assign add_ln700_12_fu_1263_p2 = ($signed(sext_ln170_15_fu_979_p1) + $signed(sext_ln700_9_fu_1259_p1));

assign add_ln700_13_fu_1269_p2 = ($signed(sext_ln170_3_fu_655_p1) + $signed(sext_ln170_4_fu_682_p1));

assign add_ln700_14_fu_1279_p2 = ($signed(sext_ln170_2_fu_628_p1) + $signed(sext_ln700_11_fu_1275_p1));

assign add_ln700_15_fu_1383_p2 = ($signed(sext_ln700_10_fu_1377_p1) + $signed(sext_ln700_12_fu_1380_p1));

assign add_ln700_16_fu_1285_p2 = ($signed(sext_ln170_6_fu_736_p1) + $signed(sext_ln170_7_fu_763_p1));

assign add_ln700_17_fu_1295_p2 = ($signed(sext_ln170_5_fu_709_p1) + $signed(sext_ln700_14_fu_1291_p1));

assign add_ln700_18_fu_1301_p2 = ($signed(sext_ln170_10_fu_844_p1) + $signed(sext_ln170_8_fu_790_p1));

assign add_ln700_19_fu_1311_p2 = ($signed(sext_ln700_fu_1195_p1) + $signed(sext_ln170_9_fu_817_p1));

assign add_ln700_1_fu_1340_p2 = ($signed(res_V_fu_1330_p3) + $signed(sext_ln700_1_fu_1337_p1));

assign add_ln700_20_fu_1321_p2 = ($signed(sext_ln700_16_fu_1307_p1) + $signed(sext_ln700_17_fu_1317_p1));

assign add_ln700_21_fu_1399_p2 = ($signed(sext_ln700_15_fu_1393_p1) + $signed(sext_ln700_18_fu_1396_p1));

assign add_ln700_22_fu_1409_p2 = ($signed(sext_ln700_13_fu_1389_p1) + $signed(sext_ln700_19_fu_1405_p1));

assign add_ln700_2_fu_1205_p2 = ($signed(sext_ln170_19_fu_1087_p1) + $signed(sext_ln170_17_fu_1033_p1));

assign add_ln700_3_fu_1215_p2 = ($signed(sext_ln170_20_fu_1114_p1) + $signed(sext_ln700_2_fu_1211_p1));

assign add_ln700_4_fu_1349_p2 = ($signed(add_ln700_1_fu_1340_p2) + $signed(sext_ln700_3_fu_1346_p1));

assign add_ln700_5_fu_1221_p2 = ($signed(sext_ln170_13_fu_925_p1) + $signed(sext_ln170_11_fu_871_p1));

assign add_ln700_6_fu_1231_p2 = ($signed(sext_ln170_18_fu_1060_p1) + $signed(sext_ln700_4_fu_1227_p1));

assign add_ln700_7_fu_1237_p2 = ($signed(sext_ln170_16_fu_1006_p1) + $signed(sext_ln170_14_fu_952_p1));

assign add_ln700_8_fu_1247_p2 = ($signed(sext_ln170_12_fu_898_p1) + $signed(sext_ln700_6_fu_1243_p1));

assign add_ln700_9_fu_1361_p2 = ($signed(sext_ln700_5_fu_1355_p1) + $signed(sext_ln700_7_fu_1358_p1));

assign add_ln700_fu_1199_p2 = ($signed(sext_ln170_22_fu_1168_p1) + $signed(sext_ln170_21_fu_1141_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((icmp_ln248_fu_252_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((icmp_ln248_fu_252_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((icmp_ln248_fu_252_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op26_read_state2 == 1'b1)) | ((icmp_ln248_fu_252_p2 == 1'd0) & (weight_V_V_TVALID == 1'b0)));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((icmp_ln271_reg_1470_pp0_iter1_reg == 1'd1) & (out_V_V_TREADY == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op26_read_state2 = ((icmp_ln252_fu_267_p2 == 1'd1) & (icmp_ln248_fu_252_p2 == 1'd0));
end

assign arg_V_read_assign_10_fu_848_p4 = {{inElem_V_fu_208[95:88]}};

assign arg_V_read_assign_11_fu_875_p4 = {{inElem_V_fu_208[103:96]}};

assign arg_V_read_assign_12_fu_902_p4 = {{inElem_V_fu_208[111:104]}};

assign arg_V_read_assign_13_fu_929_p4 = {{inElem_V_fu_208[119:112]}};

assign arg_V_read_assign_14_fu_956_p4 = {{inElem_V_fu_208[127:120]}};

assign arg_V_read_assign_15_fu_983_p4 = {{inElem_V_fu_208[135:128]}};

assign arg_V_read_assign_16_fu_1010_p4 = {{inElem_V_fu_208[143:136]}};

assign arg_V_read_assign_17_fu_1037_p4 = {{inElem_V_fu_208[151:144]}};

assign arg_V_read_assign_18_fu_1064_p4 = {{inElem_V_fu_208[159:152]}};

assign arg_V_read_assign_19_fu_1091_p4 = {{inElem_V_fu_208[167:160]}};

assign arg_V_read_assign_1_fu_578_p4 = {{inElem_V_fu_208[15:8]}};

assign arg_V_read_assign_20_fu_1118_p4 = {{inElem_V_fu_208[175:168]}};

assign arg_V_read_assign_21_fu_1145_p4 = {{inElem_V_fu_208[183:176]}};

assign arg_V_read_assign_22_fu_1172_p4 = {{inElem_V_fu_208[191:184]}};

assign arg_V_read_assign_2_fu_605_p4 = {{inElem_V_fu_208[23:16]}};

assign arg_V_read_assign_3_fu_632_p4 = {{inElem_V_fu_208[31:24]}};

assign arg_V_read_assign_4_fu_659_p4 = {{inElem_V_fu_208[39:32]}};

assign arg_V_read_assign_5_fu_686_p4 = {{inElem_V_fu_208[47:40]}};

assign arg_V_read_assign_6_fu_713_p4 = {{inElem_V_fu_208[55:48]}};

assign arg_V_read_assign_7_fu_740_p4 = {{inElem_V_fu_208[63:56]}};

assign arg_V_read_assign_8_fu_767_p4 = {{inElem_V_fu_208[71:64]}};

assign arg_V_read_assign_9_fu_794_p4 = {{inElem_V_fu_208[79:72]}};

assign arg_V_read_assign_s_fu_821_p4 = {{inElem_V_fu_208[87:80]}};

assign i_fu_258_p2 = (i_0_reg_231 + 7'd1);

assign icmp_ln248_fu_252_p2 = ((i_0_reg_231 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_267_p2 = ((nf_2_fu_204 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_281_p2 = ((sf_1_fu_200 == 32'd0) ? 1'b1 : 1'b0);

assign mul_ln1352_10_fu_838_p0 = mul_ln1352_10_fu_838_p00;

assign mul_ln1352_10_fu_838_p00 = arg_V_read_assign_s_fu_821_p4;

assign mul_ln1352_11_fu_865_p0 = mul_ln1352_11_fu_865_p00;

assign mul_ln1352_11_fu_865_p00 = arg_V_read_assign_10_fu_848_p4;

assign mul_ln1352_12_fu_892_p0 = mul_ln1352_12_fu_892_p00;

assign mul_ln1352_12_fu_892_p00 = arg_V_read_assign_11_fu_875_p4;

assign mul_ln1352_13_fu_919_p0 = mul_ln1352_13_fu_919_p00;

assign mul_ln1352_13_fu_919_p00 = arg_V_read_assign_12_fu_902_p4;

assign mul_ln1352_14_fu_946_p0 = mul_ln1352_14_fu_946_p00;

assign mul_ln1352_14_fu_946_p00 = arg_V_read_assign_13_fu_929_p4;

assign mul_ln1352_15_fu_973_p0 = mul_ln1352_15_fu_973_p00;

assign mul_ln1352_15_fu_973_p00 = arg_V_read_assign_14_fu_956_p4;

assign mul_ln1352_16_fu_1000_p0 = mul_ln1352_16_fu_1000_p00;

assign mul_ln1352_16_fu_1000_p00 = arg_V_read_assign_15_fu_983_p4;

assign mul_ln1352_17_fu_1027_p0 = mul_ln1352_17_fu_1027_p00;

assign mul_ln1352_17_fu_1027_p00 = arg_V_read_assign_16_fu_1010_p4;

assign mul_ln1352_18_fu_1054_p0 = mul_ln1352_18_fu_1054_p00;

assign mul_ln1352_18_fu_1054_p00 = arg_V_read_assign_17_fu_1037_p4;

assign mul_ln1352_19_fu_1081_p0 = mul_ln1352_19_fu_1081_p00;

assign mul_ln1352_19_fu_1081_p00 = arg_V_read_assign_18_fu_1064_p4;

assign mul_ln1352_1_fu_595_p0 = mul_ln1352_1_fu_595_p00;

assign mul_ln1352_1_fu_595_p00 = arg_V_read_assign_1_fu_578_p4;

assign mul_ln1352_20_fu_1108_p0 = mul_ln1352_20_fu_1108_p00;

assign mul_ln1352_20_fu_1108_p00 = arg_V_read_assign_19_fu_1091_p4;

assign mul_ln1352_21_fu_1135_p0 = mul_ln1352_21_fu_1135_p00;

assign mul_ln1352_21_fu_1135_p00 = arg_V_read_assign_20_fu_1118_p4;

assign mul_ln1352_22_fu_1162_p0 = mul_ln1352_22_fu_1162_p00;

assign mul_ln1352_22_fu_1162_p00 = arg_V_read_assign_21_fu_1145_p4;

assign mul_ln1352_23_fu_1189_p0 = mul_ln1352_23_fu_1189_p00;

assign mul_ln1352_23_fu_1189_p00 = arg_V_read_assign_22_fu_1172_p4;

assign mul_ln1352_2_fu_622_p0 = mul_ln1352_2_fu_622_p00;

assign mul_ln1352_2_fu_622_p00 = arg_V_read_assign_2_fu_605_p4;

assign mul_ln1352_3_fu_649_p0 = mul_ln1352_3_fu_649_p00;

assign mul_ln1352_3_fu_649_p00 = arg_V_read_assign_3_fu_632_p4;

assign mul_ln1352_4_fu_676_p0 = mul_ln1352_4_fu_676_p00;

assign mul_ln1352_4_fu_676_p00 = arg_V_read_assign_4_fu_659_p4;

assign mul_ln1352_5_fu_703_p0 = mul_ln1352_5_fu_703_p00;

assign mul_ln1352_5_fu_703_p00 = arg_V_read_assign_5_fu_686_p4;

assign mul_ln1352_6_fu_730_p0 = mul_ln1352_6_fu_730_p00;

assign mul_ln1352_6_fu_730_p00 = arg_V_read_assign_6_fu_713_p4;

assign mul_ln1352_7_fu_757_p0 = mul_ln1352_7_fu_757_p00;

assign mul_ln1352_7_fu_757_p00 = arg_V_read_assign_7_fu_740_p4;

assign mul_ln1352_8_fu_784_p0 = mul_ln1352_8_fu_784_p00;

assign mul_ln1352_8_fu_784_p00 = arg_V_read_assign_8_fu_767_p4;

assign mul_ln1352_9_fu_811_p0 = mul_ln1352_9_fu_811_p00;

assign mul_ln1352_9_fu_811_p00 = arg_V_read_assign_9_fu_794_p4;

assign mul_ln1352_fu_568_p0 = mul_ln1352_fu_568_p00;

assign mul_ln1352_fu_568_p00 = trunc_ln647_fu_557_p1;

assign nf_3_fu_541_p3 = ((icmp_ln252_fu_267_p2[0:0] === 1'b1) ? 32'd0 : nf_fu_535_p2);

assign nf_fu_535_p2 = (nf_2_fu_204 + 32'd1);

assign out_V_V_TDATA = ($signed(add_ln700_10_fu_1371_p2) + $signed(sext_ln700_20_fu_1415_p1));

assign res_V_fu_1330_p3 = ((icmp_ln271_reg_1470_pp0_iter1_reg[0:0] === 1'b1) ? 24'd0 : tmp_V_fu_196);

assign sext_ln170_10_fu_844_p1 = mul_ln1352_10_fu_838_p2;

assign sext_ln170_11_fu_871_p1 = mul_ln1352_11_fu_865_p2;

assign sext_ln170_12_fu_898_p1 = mul_ln1352_12_fu_892_p2;

assign sext_ln170_13_fu_925_p1 = mul_ln1352_13_fu_919_p2;

assign sext_ln170_14_fu_952_p1 = mul_ln1352_14_fu_946_p2;

assign sext_ln170_15_fu_979_p1 = mul_ln1352_15_fu_973_p2;

assign sext_ln170_16_fu_1006_p1 = mul_ln1352_16_fu_1000_p2;

assign sext_ln170_17_fu_1033_p1 = mul_ln1352_17_fu_1027_p2;

assign sext_ln170_18_fu_1060_p1 = mul_ln1352_18_fu_1054_p2;

assign sext_ln170_19_fu_1087_p1 = mul_ln1352_19_fu_1081_p2;

assign sext_ln170_1_fu_601_p1 = mul_ln1352_1_fu_595_p2;

assign sext_ln170_20_fu_1114_p1 = mul_ln1352_20_fu_1108_p2;

assign sext_ln170_21_fu_1141_p1 = mul_ln1352_21_fu_1135_p2;

assign sext_ln170_22_fu_1168_p1 = mul_ln1352_22_fu_1162_p2;

assign sext_ln170_2_fu_628_p1 = mul_ln1352_2_fu_622_p2;

assign sext_ln170_3_fu_655_p1 = mul_ln1352_3_fu_649_p2;

assign sext_ln170_4_fu_682_p1 = mul_ln1352_4_fu_676_p2;

assign sext_ln170_5_fu_709_p1 = mul_ln1352_5_fu_703_p2;

assign sext_ln170_6_fu_736_p1 = mul_ln1352_6_fu_730_p2;

assign sext_ln170_7_fu_763_p1 = mul_ln1352_7_fu_757_p2;

assign sext_ln170_8_fu_790_p1 = mul_ln1352_8_fu_784_p2;

assign sext_ln170_9_fu_817_p1 = mul_ln1352_9_fu_811_p2;

assign sext_ln170_fu_574_p1 = mul_ln1352_fu_568_p2;

assign sext_ln700_10_fu_1377_p1 = $signed(add_ln700_12_reg_1615);

assign sext_ln700_11_fu_1275_p1 = $signed(add_ln700_13_fu_1269_p2);

assign sext_ln700_12_fu_1380_p1 = $signed(add_ln700_14_reg_1620);

assign sext_ln700_13_fu_1389_p1 = $signed(add_ln700_15_fu_1383_p2);

assign sext_ln700_14_fu_1291_p1 = $signed(add_ln700_16_fu_1285_p2);

assign sext_ln700_15_fu_1393_p1 = $signed(add_ln700_17_reg_1625);

assign sext_ln700_16_fu_1307_p1 = $signed(add_ln700_18_fu_1301_p2);

assign sext_ln700_17_fu_1317_p1 = $signed(add_ln700_19_fu_1311_p2);

assign sext_ln700_18_fu_1396_p1 = $signed(add_ln700_20_reg_1630);

assign sext_ln700_19_fu_1405_p1 = $signed(add_ln700_21_fu_1399_p2);

assign sext_ln700_1_fu_1337_p1 = $signed(add_ln700_reg_1595);

assign sext_ln700_20_fu_1415_p1 = $signed(add_ln700_22_fu_1409_p2);

assign sext_ln700_2_fu_1211_p1 = $signed(add_ln700_2_fu_1205_p2);

assign sext_ln700_3_fu_1346_p1 = $signed(add_ln700_3_reg_1600);

assign sext_ln700_4_fu_1227_p1 = $signed(add_ln700_5_fu_1221_p2);

assign sext_ln700_5_fu_1355_p1 = $signed(add_ln700_6_reg_1605);

assign sext_ln700_6_fu_1243_p1 = $signed(add_ln700_7_fu_1237_p2);

assign sext_ln700_7_fu_1358_p1 = $signed(add_ln700_8_reg_1610);

assign sext_ln700_8_fu_1367_p1 = $signed(add_ln700_9_fu_1361_p2);

assign sext_ln700_9_fu_1259_p1 = $signed(add_ln700_11_fu_1253_p2);

assign sext_ln700_fu_1195_p1 = mul_ln1352_23_fu_1189_p2;

assign sf_fu_521_p2 = (32'd1 + sf_1_fu_200);

assign tmp_V_3_fu_1419_p2 = ($signed(add_ln700_10_fu_1371_p2) + $signed(sext_ln700_20_fu_1415_p1));

assign trunc_ln647_fu_557_p1 = inElem_V_fu_208[7:0];

assign wgt_M_instance_0_V_fu_287_p1 = weight_V_V_TDATA[3:0];

endmodule //StreamingFCLayer_Batch_3_Matrix_Vector_Activa
