// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGenerator1D_0_ConvolutionInputGene_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V_V_TDATA,
        in_V_V_TVALID,
        in_V_V_TREADY,
        out_V_V_TDATA,
        out_V_V_TVALID,
        out_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_V_V_TDATA;
input   in_V_V_TVALID;
output   in_V_V_TREADY;
output  [15:0] out_V_V_TDATA;
output   out_V_V_TVALID;
input   out_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_TREADY;
reg out_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln1687_fu_152_p2;
wire   [0:0] icmp_ln1689_fu_167_p2;
wire   [0:0] icmp_ln1725_fu_216_p2;
reg    out_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln1689_reg_511;
reg   [6:0] i_0_0_reg_107;
reg    ap_predicate_op42_read_state2;
reg    ap_predicate_op53_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] add_ln1687_fu_158_p2;
wire   [1:0] trunc_ln1710_fu_176_p1;
reg   [1:0] trunc_ln1710_reg_515;
reg   [0:0] icmp_ln1725_reg_522;
wire   [3:0] tmp_V_2_fu_222_p1;
reg   [3:0] tmp_V_2_reg_526;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [31:0] inp_13_0_fu_62;
wire   [31:0] select_ln1720_fu_198_p3;
wire   [31:0] add_ln1694_fu_293_p2;
reg   [31:0] ofm_y_1_0_fu_66;
wire   [31:0] select_ln1720_1_fu_207_p3;
reg   [31:0] read_block_1_0_fu_70;
wire   [31:0] add_ln1733_fu_229_p2;
wire   [31:0] add_ln1700_fu_319_p2;
reg   [31:0] current_block_write_s_fu_74;
wire   [31:0] select_ln1735_fu_241_p3;
wire   [31:0] select_ln1697_fu_311_p3;
reg   [3:0] inputBuf_0_V_fu_78;
wire   [3:0] tmp_V_fu_259_p1;
wire   [1:0] trunc_ln321_fu_263_p1;
reg   [3:0] inputBuf_1_V_fu_82;
reg   [3:0] inputBuf_2_V_fu_86;
reg   [3:0] inputBuf_3_V_fu_90;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] add_ln1719_fu_186_p2;
wire   [0:0] icmp_ln1720_fu_192_p2;
wire   [31:0] add_ln1710_fu_180_p2;
wire   [0:0] icmp_ln1735_fu_235_p2;
wire   [31:0] add_ln1696_fu_299_p2;
wire   [0:0] icmp_ln1697_fu_305_p2;
wire   [1:0] tmp_1_fu_357_p5;
wire   [1:0] tmp_2_fu_376_p5;
wire   [1:0] tmp_3_fu_395_p5;
wire   [3:0] tmp_3_fu_395_p6;
wire   [3:0] tmp_2_fu_376_p6;
wire   [3:0] tmp_1_fu_357_p6;
wire   [11:0] tmp_V_1_fu_409_p4;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_362;
reg    ap_condition_367;
reg    ap_condition_370;
reg    ap_condition_373;
reg    ap_condition_376;
reg    ap_condition_379;
reg    ap_condition_382;
reg    ap_condition_385;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

ConvolutionInputGenerator1D_0_ConvolutionInputGenerator1D_0_mux_42_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
ConvolutionInputGenerator1D_0_mux_42_4_1_1_U1(
    .din0(inputBuf_0_V_fu_78),
    .din1(inputBuf_1_V_fu_82),
    .din2(inputBuf_2_V_fu_86),
    .din3(inputBuf_3_V_fu_90),
    .din4(tmp_1_fu_357_p5),
    .dout(tmp_1_fu_357_p6)
);

ConvolutionInputGenerator1D_0_ConvolutionInputGenerator1D_0_mux_42_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
ConvolutionInputGenerator1D_0_mux_42_4_1_1_U2(
    .din0(inputBuf_0_V_fu_78),
    .din1(inputBuf_1_V_fu_82),
    .din2(inputBuf_2_V_fu_86),
    .din3(inputBuf_3_V_fu_90),
    .din4(tmp_2_fu_376_p5),
    .dout(tmp_2_fu_376_p6)
);

ConvolutionInputGenerator1D_0_ConvolutionInputGenerator1D_0_mux_42_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
ConvolutionInputGenerator1D_0_mux_42_4_1_1_U3(
    .din0(inputBuf_0_V_fu_78),
    .din1(inputBuf_1_V_fu_82),
    .din2(inputBuf_2_V_fu_86),
    .din3(inputBuf_3_V_fu_90),
    .din4(tmp_3_fu_395_p5),
    .dout(tmp_3_fu_395_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_74 <= select_ln1697_fu_311_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_block_write_s_fu_74 <= select_ln1735_fu_241_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_s_fu_74 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_0_reg_107 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_0_reg_107 <= add_ln1687_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_13_0_fu_62 <= add_ln1694_fu_293_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd0) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inp_13_0_fu_62 <= select_ln1720_fu_198_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_13_0_fu_62 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_367)) begin
            inputBuf_0_V_fu_78 <= tmp_V_2_reg_526;
        end else if ((1'b1 == ap_condition_362)) begin
            inputBuf_0_V_fu_78 <= tmp_V_fu_259_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_373)) begin
            inputBuf_1_V_fu_82 <= tmp_V_2_reg_526;
        end else if ((1'b1 == ap_condition_370)) begin
            inputBuf_1_V_fu_82 <= tmp_V_fu_259_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_379)) begin
            inputBuf_2_V_fu_86 <= tmp_V_2_reg_526;
        end else if ((1'b1 == ap_condition_376)) begin
            inputBuf_2_V_fu_86 <= tmp_V_fu_259_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((1'b1 == ap_condition_385)) begin
            inputBuf_3_V_fu_90 <= tmp_V_2_reg_526;
        end else if ((1'b1 == ap_condition_382)) begin
            inputBuf_3_V_fu_90 <= tmp_V_fu_259_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd0) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ofm_y_1_0_fu_66 <= select_ln1720_1_fu_207_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_0_fu_66 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_70 <= add_ln1700_fu_319_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        read_block_1_0_fu_70 <= add_ln1733_fu_229_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_1_0_fu_70 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1687_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1689_reg_511 <= icmp_ln1689_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1725_reg_522 <= icmp_ln1725_fu_216_p2;
        trunc_ln1710_reg_515 <= trunc_ln1710_fu_176_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_V_2_reg_526 <= tmp_V_2_fu_222_p1;
    end
end

always @ (*) begin
    if ((icmp_ln1687_fu_152_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_V_V_TDATA_blk_n = in_V_V_TVALID;
    end else begin
        in_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op42_read_state2 == 1'b1)))) begin
        in_V_V_TREADY = 1'b1;
    end else begin
        in_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1689_reg_511 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_TDATA_blk_n = out_V_V_TREADY;
    end else begin
        out_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1689_reg_511 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_V_TVALID = 1'b1;
    end else begin
        out_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln1687_fu_152_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln1687_fu_152_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1687_fu_158_p2 = (i_0_0_reg_107 + 7'd1);

assign add_ln1694_fu_293_p2 = (inp_13_0_fu_62 + 32'd1);

assign add_ln1696_fu_299_p2 = (current_block_write_s_fu_74 + 32'd1);

assign add_ln1700_fu_319_p2 = (read_block_1_0_fu_70 + 32'd1);

assign add_ln1710_fu_180_p2 = (32'd1 + current_block_write_s_fu_74);

assign add_ln1719_fu_186_p2 = (32'd1 + ofm_y_1_0_fu_66);

assign add_ln1733_fu_229_p2 = (read_block_1_0_fu_70 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op42_read_state2 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op42_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op42_read_state2 == 1'b1)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((in_V_V_TVALID == 1'b0) & (ap_predicate_op53_read_state2 == 1'b1)) | ((in_V_V_TVALID == 1'b0) & (ap_predicate_op42_read_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln1689_reg_511 == 1'd0) & (out_V_V_TREADY == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_362 = ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln321_fu_263_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_367 = ((trunc_ln1710_reg_515 == 2'd0) & (icmp_ln1725_reg_522 == 1'd1) & (icmp_ln1689_reg_511 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_370 = ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln321_fu_263_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_373 = ((trunc_ln1710_reg_515 == 2'd1) & (icmp_ln1725_reg_522 == 1'd1) & (icmp_ln1689_reg_511 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_376 = ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln321_fu_263_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_379 = ((trunc_ln1710_reg_515 == 2'd2) & (icmp_ln1725_reg_522 == 1'd1) & (icmp_ln1689_reg_511 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_382 = ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln321_fu_263_p1 == 2'd3));
end

always @ (*) begin
    ap_condition_385 = ((trunc_ln1710_reg_515 == 2'd3) & (icmp_ln1725_reg_522 == 1'd1) & (icmp_ln1689_reg_511 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op42_read_state2 = ((icmp_ln1725_fu_216_p2 == 1'd1) & (icmp_ln1689_fu_167_p2 == 1'd0) & (icmp_ln1687_fu_152_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op53_read_state2 = ((icmp_ln1689_fu_167_p2 == 1'd1) & (icmp_ln1687_fu_152_p2 == 1'd0));
end

assign icmp_ln1687_fu_152_p2 = ((i_0_0_reg_107 == 7'd67) ? 1'b1 : 1'b0);

assign icmp_ln1689_fu_167_p2 = ((inp_13_0_fu_62 < 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln1697_fu_305_p2 = ((add_ln1696_fu_299_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln1720_fu_192_p2 = ((add_ln1719_fu_186_p2 == 32'd64) ? 1'b1 : 1'b0);

assign icmp_ln1725_fu_216_p2 = ((read_block_1_0_fu_70 < 32'd66) ? 1'b1 : 1'b0);

assign icmp_ln1735_fu_235_p2 = ((add_ln1710_fu_180_p2 == 32'd4) ? 1'b1 : 1'b0);

assign out_V_V_TDATA = tmp_V_1_fu_409_p4;

assign select_ln1697_fu_311_p3 = ((icmp_ln1697_fu_305_p2[0:0] === 1'b1) ? 32'd0 : add_ln1696_fu_299_p2);

assign select_ln1720_1_fu_207_p3 = ((icmp_ln1720_fu_192_p2[0:0] === 1'b1) ? 32'd0 : add_ln1719_fu_186_p2);

assign select_ln1720_fu_198_p3 = ((icmp_ln1720_fu_192_p2[0:0] === 1'b1) ? 32'd0 : inp_13_0_fu_62);

assign select_ln1735_fu_241_p3 = ((icmp_ln1735_fu_235_p2[0:0] === 1'b1) ? 32'd0 : add_ln1710_fu_180_p2);

assign tmp_1_fu_357_p5 = (2'd1 + trunc_ln1710_reg_515);

assign tmp_2_fu_376_p5 = (trunc_ln1710_reg_515 ^ 2'd2);

assign tmp_3_fu_395_p5 = (2'd3 + trunc_ln1710_reg_515);

assign tmp_V_1_fu_409_p4 = {{{tmp_3_fu_395_p6}, {tmp_2_fu_376_p6}}, {tmp_1_fu_357_p6}};

assign tmp_V_2_fu_222_p1 = in_V_V_TDATA[3:0];

assign tmp_V_fu_259_p1 = in_V_V_TDATA[3:0];

assign trunc_ln1710_fu_176_p1 = current_block_write_s_fu_74[1:0];

assign trunc_ln321_fu_263_p1 = current_block_write_s_fu_74[1:0];

endmodule //ConvolutionInputGenerator1D_0_ConvolutionInputGene_1
